name: Pages
on:
  push:
    branches:
    - kedar/docs
    - tpulkit/docs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        - docs-folder: "docs/"
            pre-build-command: "pip install sphinx-rtd-theme && sphinx-apidoc -o docs/source/module_name module_name"
            build-command: "make html"
        -
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages